<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOGh6yiA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOGh6yiA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOGh6yiA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOGh6yiA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOGh6yiA\App_KernelDevDebugContainer([
    'container.build_hash' => 'OGh6yiA',
    'container.build_id' => '26927750',
    'container.build_time' => 1783939110,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOGh6yiA');
